# Generated by Django 4.0.6 on 2022-12-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0002_remove_product_prod_product_description_product_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='situation',
            old_name='age',
            new_name='human',
        ),
    ]
