# Generated by Django 4.0.6 on 2022-12-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0004_savat_remove_product_cash_category_til_human_til_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='age',
            name='til',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='lang',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
