# Generated by Django 4.0.6 on 2023-01-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0005_age_til_alter_user_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='til',
            field=models.IntegerField(default=1),
        ),
    ]
