# Generated by Django 4.0.6 on 2023-01-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0006_cash_til'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
