# Generated by Django 4.0.6 on 2023-01-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0007_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='age',
            old_name='age',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='cash',
            old_name='cash',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_uz',
        ),
        migrations.RenameField(
            model_name='human',
            old_name='content',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='interests',
            old_name='content',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='description_ru',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='situation',
            old_name='content',
            new_name='name_ru',
        ),
        migrations.RemoveField(
            model_name='age',
            name='til',
        ),
        migrations.RemoveField(
            model_name='cash',
            name='til',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='til',
        ),
        migrations.RemoveField(
            model_name='human',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='human',
            name='til',
        ),
        migrations.RemoveField(
            model_name='interests',
            name='til',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='til',
        ),
        migrations.RemoveField(
            model_name='situation',
            name='til',
        ),
        migrations.AddField(
            model_name='age',
            name='name_uz',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='cash',
            name='name_uz',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='human',
            name='name_uz',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interests',
            name='name_uz',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='situation',
            name='name_uz',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
