# Generated by Django 4.0.6 on 2023-01-13 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0008_rename_age_age_name_ru_rename_cash_cash_name_ru_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Age',
            new_name='Agee',
        ),
    ]
